### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by afriapps** [spookylukey/django-paypal#103]
Im using Django 1.8.4, so when doing pip install django-paypal it installs south. That breaks things, so I pip uninstall south. Then it works. But I cannot import the follwing:

from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received

No module named standard.models

It works if I import it from shell within my virtualenv

**Comment by spookylukey** [comment]
I'm not sure why having South breaks things - it should be possible to just ignore it.

See issue #101 for why it is there. I'll revisit that and remove it from setup.py as a dependency.

However, that doesn't explain your second issue. I can run the test suite with South not installed and it works fine. I have other projects where I've also uninstalled South and they use django-paypal without any issue. You'll need to investigate more to show this is an issue with django-paypal.

**Comment by spookylukey** [comment]
South is no longer a dependency for django-paypal.
