### ISSUE TITLE
SHA-256 compliance

### ISSUE THREAD

**Issue by gio82** [spookylukey/django-paypal#104]
Hi @spookylukey ,

is this already compliant to new paypal security upgrade?

https://www.paypal-knowledge.com/resources/sites/PAYPAL/content/live/FAQ/1000/FAQ1766/en_US/2015%20Merchant%20Security%20System%20Upgrade%20Guide%20%28U.S.%20English%29.pdf

thanks

**Comment by spookylukey** [comment]
Yes, django-paypal doesn't work on this level. You will have to test your system to know.
