### ISSUE TITLE
Using a different locale breaks the callback from paypal

### ISSUE THREAD

**Issue by palkeo** [spookylukey/django-paypal#105]
Hi,

We run django-paypal on a website with a fr_FR locale. When django-paypal receive the callback from paypal, that confirms that the payment has been made, it tries to parse the date from paypal using PAYPAL_DATE_FORMAT (defined in standard/forms.py).

However, as my locale is fr_FR, it is expecting the names in the date in french, and it fails. It returns that an invalid ipn is received…
If I turn my locale to en_US, everything works fine.

Could you fix that problem ? (probably by setting the locale to "C" before parsing the dates, and setting it back to its original value after ?).

Thanks,
palkeo.

**Comment by xaviergmail** [comment]
:+1: I would also like to see this. I am not yet using django-paypal, but I plan on doing so in just a few hours and this could be a slight issue.

**Comment by spookylukey** [comment]
If you can tell me exactly what it means for you to run your site under fr_FR locale, I could try to look at the issue.

**Comment by palkeo** [comment]
On the settings.py of the website, there is :
« import locale; locale.setlocale(locale.LC_ALL, ('fr_FR', 'UTF-8')) » (should be equivalent to the server's locale in french).

Also, the LANGUAGE_CODE is « fr-fr ».

That should be sufficient to reproduce the bug !
Thanks :)

**Comment by xaviergmail** [comment]
Ah, my server's locale is in English, but my project's LANGUAGE_CODE is 'fr'. I did not realize the distinction between the two. False alarm.. No issues here!

**Comment by spookylukey** [comment]
OK, I'm able to reproduce the bug in a test now. However, fixing it is hard - see https://code.djangoproject.com/ticket/13339#comment:11

**Comment by spookylukey** [comment]
Possibly relevant:

http://stackoverflow.com/questions/18593661/how-do-i-strftime-a-date-object-in-a-different-locale
http://babel.pocoo.org/docs/api/dates/?highlight=parse#basic-parsing

Or we might just have to implement our own parsing for the formats PayPal sends.

**Comment by spookylukey** [comment]
@palkeo  I'd be really grateful if you could test the fix in 9158a9ed7620a04440af574d65cb3da9a1a76c9b - thanks!

**Comment by spookylukey** [comment]
This was fixed in 9158a9e , I forgot to close this.
