### ISSUE TITLE
"Optional" variables are actually required?

### ISSUE THREAD

**Issue by lianhuilui** [spookylukey/django-paypal#106]
The following fields are listed as optional on paypal but when I click "Buy Now", it shows they are required:
a1, p1, t1, a2, p2, t2, a3, p3, t3, src, sra, modify, no_note, lc, page_style, cbt, custom, cmd, invoice, return_url

**Comment by spookylukey** [comment]
Please see the docs for how to use IPN/PDT:

https://django-paypal.readthedocs.org/en/stable/

**Comment by lianhuilui** [comment]
I followed the docs but those fields show up as required. I am using form wizard and this is the final form of the wizard. I don't know if they are compatible?

**Comment by spookylukey** [comment]
No, the django-paypal form is not a normal django form - it is never used to receive POST requests, only to create a button that is a link to PayPal. You have to use it as it says in the docs, using `{{ form.render }}`. This would presumably be **after** the last step in your form wizard code.
