### ISSUE TITLE
"return_url" does not get passed correctly

### ISSUE THREAD

**Issue by lianhuilui** [spookylukey/django-paypal#107]
When passing "return_url", it renders this input tag:
`<input id="id_payment-return_url" name="return" type="hidden" value="return-url-here">`

which shows an "return_url is required" error message.

Changing the name to `payment-return_url` removes this error.

**Comment by spookylukey** [comment]
Please see the docs for how to use IPN/PDT:

https://django-paypal.readthedocs.org/en/stable/

**Comment by inoks** [comment]
Seems default example for IPN payments should be updated, as it's not works now, since variables are not properly defined:
~~~
    # What you want the button to do.
    paypal_dict = {
        "business": "receiver_email@example.com",
        "amount": "10000000.00",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": "https://www.example.com" + reverse('paypal-ipn'),
        "return_url": "https://www.example.com/your-return-location/",
        "cancel_return": "https://www.example.com/your-cancel-location/",
        "custom": "Upgrade all users!",  # Custom command to correlate to some function later (optional)
    }
~~~
https://django-paypal.readthedocs.io/en/stable/standard/ipn.html

And docs at https://django-paypal.readthedocs.org/en/stable/ does not  have clear information about variable names.

**Comment by spookylukey** [comment]
@inoks - your comments seem to be about something different from the original post, please create a new issue. But please include exact details, I can't guess what is wrong. In addition, the docs do have clear information about variable names. [This page](https://django-paypal.readthedocs.io/en/stable/standard/ipn.html) links to the PayPal docs, which are best source. To quote:

> For a full list of variables that can be used in paypal_dict, see [PayPal HTML variables documentation](https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/)

**Comment by inoks** [comment]
@spookylukey No, my problem was i try t send form data back to Django, instead of `PAYPAL_ENDPOINT` via `form.get_endpoint()`.
