### ISSUE TITLE
_xclick is not a valid choice

### ISSUE THREAD

**Issue by lianhuilui** [spookylukey/django-paypal#108]
The following error occurs:
`(Hidden field cmd) Select a valid choice. _xclick is not one of the available choices.`

even when the variable is set manually. _cart shows a similar message.

**Comment by spookylukey** [comment]
You will need to explain what you are doing more clearly.

**Comment by spookylukey** [comment]
Please see the docs for how to use IPN/PDT:

https://django-paypal.readthedocs.org/en/stable/

**Comment by inoks** [comment]
@spookylukey There no related information of how to provide `cmd` value in current version of docs. 
@lianhuilui Did you find how to set `cmd` properly?

**Comment by spookylukey** [comment]
Yes, there is. If you read the docs, it links to the PayPal docs (which we are not going to duplicate), which documents the options for `cmd`. See https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#technical-variables

**Comment by inoks** [comment]
Ok, created PR #155 to make docs more clear.
