### ISSUE TITLE
Change button text from 'Buy Now' to 'Pay Now'

### ISSUE THREAD

**Issue by Arlus** [spookylukey/django-paypal#110]
Is there a way to change the text for the paypal IPN checkout button?

**Comment by spookylukey** [comment]
At the moment, the only way to do this would be to subclass `PayPalPaymentsForm` and change the `get_image` method. However, if you wanted to submit a patch to make it easier (e.g. by passing a custom image URL to the constructor of `PayPalPaymentsForm`), that would be accepted.
