### ISSUE TITLE
Check paid price in the post signal.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [spookylukey/django-paypal#126]
I want to ask if it is a good idea to check the payed price in the post signal.

```python
 order = Order.objects.get(uuid=ipn_obj.uuid)
        if ipn_obj.amount  == order.get_price():
```
Because users can change the amount of money send by the form. It seems to me like an important security trick. Is it a good idea to add it to the documentation?

:beers:

**Comment by spookylukey** [comment]
Yes, it would be good to say something broader - that users are able to change many things about the payment that is actually made, including the price, so these things should be checked. Patch welcome!
