### ISSUE TITLE
Custom and transaction_subject must have max_length=256.

### ISSUE THREAD

**Issue by kalekseev** [spookylukey/django-paypal#127]
From paypal ipn docs https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/

>  The length of the custom variable is limited to 256 characters.

Currently this fields have max_length=255.

**Comment by spookylukey** [comment]
Patch would be accepted, it will need migrations for Django 1.7+ and for south.

**Comment by spookylukey** [comment]
I can work on this actually.

**Comment by spookylukey** [comment]
This is fixed in 80a05f6b5a3e7522d19a44d9cef4da8b2d63c417
