### ISSUE TITLE
does not support option_selectionX variable

### ISSUE THREAD

**Issue by nileshbits** [spookylukey/django-paypal#129]
(Not to be confused with the Mass Pay variables option_selectionX_Y)

These are the selections corresponding to option_nameX which you already handle. I think these variables were just missed for some reason.

**Comment by spookylukey** [comment]
They are supported, like all 'fooX' options (i.e. fields with variable number of items), via posted_data_dict.

The option_name1 and option_name2 fields ought to be removed, and the documentation for IPN/PDT needs updating regarding this.

**Comment by spookylukey** [comment]
Sorry, these fields ought to be supported, since only 2 are listed, rather than a variable number like X. I'll add them shortly.

**Comment by spookylukey** [comment]
I've fixed this now on the master branch.
