### ISSUE TITLE
BUG: Does PDT's return url has @csrf_exempt ?

### ISSUE THREAD

**Issue by girishkumarkh** [spookylukey/django-paypal#133]
While testing PDT return call after paypal payment is gone through the code leads us into CSRF verification failed. There is possibility of bug here.
Ref:
https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/pdt/views.py#L29

**Comment by spookylukey** [comment]
I don't understand what you are saying. For PDT, PayPal sends a GET request to that view, as far as I know, and as far as the docs say:

https://developer.paypal.com/webapps/developer/docs/classic/products/payment-data-transfer/

**Comment by girishkumarkh** [comment]
Perhaps, It might be my sandbox environment - Whenever I try testing payment via PDT I end up getting **CSRF verification failed** error for some reason.

**Comment by spookylukey** [comment]
Closing because this doesn't seem to be a bug in django-paypal
