### ISSUE TITLE
IPN Response error "Invalid form. (for_auction: Enter a number.)" is wrong

### ISSUE THREAD

**Issue by Eugnis** [spookylukey/django-paypal#134]
The IPN for_auction variable should return only true or false without any numbers (https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/#id091EBJ0H0Y4)

**Comment by spookylukey** [comment]
The docs don't actually say what is accepted there, but I'll accept your word for it. A patch would be accepted.
