### ISSUE TITLE
IPN Invalid receiver_email

### ISSUE THREAD

**Issue by jranck88** [spookylukey/django-paypal#135]
Has anyone else been having a problem with flagged IPN transactions reporting "Invalid receiver_email" through Payments Standard?

I'm running a bit of a custom set up through django-merchant and plata and regardless of sandbox vs production, sandbox account vs actual account, I'm consistently getting the receiver_email flag.

I've had to resort to checking both valid and invalid signals for Completed transactions, which works but seems a bit off.

Could possibly jump in here and help with a pull request if others are seeing this and no work hasn't been done.

Overall love the app, thanks for putting so much work in!

**Comment by E-M-P-I-R-E** [comment]
Hi Joel,

Fellow user here.

Have you double/triple checked that you're not using sandbox button,
accidentally, or your `PAYPAL_RECEIVER_EMAIL` or `PAYPAL_TEST` settings are
set incorrectly?

Hope it helps.

**Comment by spookylukey** [comment]
Without more info, this doesn't seem to be actionable as the problem can't be reproduce by anyone else.
