### ISSUE TITLE
Nothing is returned from PayPal, using GET or POST callback

### ISSUE THREAD

**Issue by tezro** [spookylukey/django-paypal#142]
Hello, it's most likely not django-paypal error, but... In PayPal settings I tried both POST and GET parameters to be returned to the server and in both cases nothing is passed back.

Is there anything I'm not doing correctly?

When in settings it's set to POST, the call back request is doing GET and obviously nothing is there. When it's set to GET — there's nothing in the `return_url` url parameters.

Django 1.8.11, latest django-paypal, sandboxed PayPal busines account.

Thanks ahead.

**Comment by spookylukey** [comment]
You need to describe your problem more clearly. Are you using IPN or PDT, for a start?

**Comment by tezro** [comment]
Oh, sorry. Yeah PDT.

In `settings` all of these are set to actual values:
```
# PayPal.
PAYPAL_TEST = True
PAYPAL_IDENTITY_TOKEN = '...'
PAYPAL_CLIENT_ID = '..'
PAYPAL_SECRET = '...'
PAYPAL_RECEIVER_EMAIL = '...'
```
And in the `views`:
```
def pre_paypal_view(request, four_id):
    paypal_dict = {
        "business": settings.PAYPAL_RECEIVER_EMAIL,
        "amount": '0.01',   # Only for test
        "item_name": "item_name",
        "invoice": "unique_invoice",
        "cancel_return": '...',
        "return_url": '...',
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {
        'form': form,
    }
    return render(request, 'pre_paypal.html', context)
```
The `return_url_view` is pretty much by the docs and I'm logging the request on dev server and staging one in `DEBUG` mode.

After redirecting to PayPal the sandbox transaction happens normally and is being redirected back to the correct URL. Without POST or GET data.

Hope that helps.

**Comment by spookylukey** [comment]
What is the exact `return_url` you are using?

**Comment by tezro** [comment]
http://sala.svelteteam.com/exhibition-registration-payment-success/1473/

**Comment by spookylukey** [comment]
OK, I don't know what is going wrong, except that I wouldn't rely on the sandbox to do anything correctly. Remember that you will need to enable PDT on your sandbox account, which is quite separate from your main account.  django-paypal only supports having `tx` as a GET parameter, not POST. I'm afraid I can't provide any more support than this, unless you can show there is a bug in django-paypal.

**Comment by tezro** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/188876/14171494/d720806a-f77a-11e5-914c-7fbdc7d74e13.png)

Sandbox account. PDT enabled. Test payments go through, but no data comes back in return.
