### ISSUE TITLE
django >= 1.10 usage of _default_manager

### ISSUE THREAD

**Issue by rsalmaso** [spookylukey/django-paypal#147]
Under django >= 1.10 ipn_obj._default_manager in paypal.standard.helpers.duplicate_txn_id fails because managers are not accessible from instances.

See https://code.djangoproject.com/ticket/26652

**Comment by spookylukey** [comment]
This should be fixed now, as above, thanks for the report. The build is currently failing due to a different issue with the sandbox PayPal account that is used in the tests.

**Comment by manikos** [comment]
Should we wait for the 0.3.3 release for this error to be fixed or do a `pip install git+https://github.com/spookylukey/django-paypal.git`?

**Comment by spookylukey** [comment]
0.3.3 released now.

**Comment by manikos** [comment]
Great! Thanks a lot!!!
