### ISSUE TITLE
 UnicodeDecodeError at /paypal/ ‘ascii’ codec can't decode byte

### ISSUE THREAD

**Issue by khrizo** [spookylukey/django-paypal#153]
Not sure what could be the issue.

django 1.8.13
django-paypal 0.3.2
requests 2.10.0

using 'paypal.standard.ipn'

UnicodeDecodeError at /paypal/ ‘ascii’ codec can't decode byte 0xf4 in position 1: ordinal not in range(128)

**Comment by spookylukey** [comment]
You need to provide a lot more information - particularly, the complete stack trace, and any code in that is a part of that stack trace which isn't django or django-paypal code.

**Comment by khrizo** [comment]
Thank you for the quick response, here is the trace:

Internal Server Error: /confirm/paypal/ Traceback (most recent call last):

File "/home/modler/lib/python2.7/django/core/handlers/base.py", line 132, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/modler/lib/python2.7/django/views/decorators/http.py", line 45, in inner
  return func(request, *args, **kwargs)
File "/home/modler/lib/python2.7/django/views/decorators/csrf.py", line 58, in wrapped_view
  return view_func(*args, **kwargs)
File "/home/modler/lib/python2.7/paypal/standard/ipn/views.py", line 76, in ipn
  ipn_obj.initialize(request)
File "/home/modler/lib/python2.7/paypal/standard/models.py", line 379, in initialize
  self.query = request.body.decode('ascii')
UnicodeDecodeError: ‘ascii’ codec can't decode byte 0×88 in position 0: ordinal not in range(128)

Request repr(): <WSGIRequest path:/confirm/paypal/, GET:<QueryDict: {}>, POST:<QueryDict: {u'\ufffdn\ufffd\x18)\x03': [u'']}>, COOKIES:{}, META:{'CONTENT_LENGTH': ‘6’,

'CONTENT_TYPE': 'application/x-www-form-urlencoded',
'CONTEXT_DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'cVjsKTiB5W7cKwz7VL5QYOnzfB32iAyc',
'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_CONNECTION': 'close',
'HTTP_CORRELATION_ID': '28f389109db39',
'HTTP_FORWARDED_REQUEST_URI': '/confirm/paypal/',
'HTTP_HOST': 'domainxxxx.com',
'HTTP_HTTPS': 'on',
'HTTP_HTTP_X_FORWARDED_PROTO': 'https',
'HTTP_USER_AGENT': 'PayPal IPN ( https://www.paypal.com/ipn )',
'HTTP_X_FORWARDED_FOR': '173.0.81.1',
'HTTP_X_FORWARDED_HOST': 'domainxxxx.com',
'HTTP_X_FORWARDED_PROTO': 'https',
'HTTP_X_FORWARDED_SERVER': 'domainxxxx.com',
'HTTP_X_FORWARDED_SSL': 'on',
'LD_LIBRARY_PATH': '/home/modler/webapps/cms/apache2/lib:/home/modler/webapps/cms/lib',
'PATH_INFO': u'/confirm/paypal/',
'PATH_TRANSLATED': '/home/modler/webapps/cms/landing/landing/wsgi.py/confirm/paypal/',
'QUERY_STRING': '',
'REMOTE_ADDR': '127.0.0.1',
'REMOTE_PORT': '55679',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/confirm/paypal/',
'SCRIPT_FILENAME': '/home/modler/webapps/cms/landing/landing/wsgi.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://domainxxxx.com/confirm/paypal/',
'SCRIPT_URL': '/confirm/paypal/',
'SERVER_ADDR': '127.0.0.1',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'domainxxxx.com',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.17 (Unix) mod_wsgi/4.4.21 Python/2.7.5',
'apache.version': (2, 4, 17),
'mod_wsgi.application_group': 'web1.webfaction.com|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.daemon_connects': '1',
'mod_wsgi.daemon_restarts': '0',
'mod_wsgi.daemon_start': '1468296323125809',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '20753',
'mod_wsgi.path_info': '/confirm/paypal/',
'mod_wsgi.process_group': 'cms',
'mod_wsgi.queue_start': '1468296323125669',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.request_start': '1468296323125448',
'mod_wsgi.script_name': '',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.script_start': '1468296323599101',
'mod_wsgi.version': (4, 4, 21),
'wsgi.errors': <mod_wsgi.Log object at 0x7fc704e2fc00>,
'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
'wsgi.input': <mod_wsgi.Input object at 0x7fc70624fda0>,
'wsgi.multiprocess': True,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'https',
'wsgi.version': (1, 0)}>

**Comment by spookylukey** [comment]
Hmm, somehow you are getting non-ASCII data to that endpoint. PayPal does not do this, it always sends it url-encoded which will always be ASCII. You'll need to put some debugging in to print the actual content of request.body, and also provide information about how this view is being called. It should be wired up to receive data only from PayPal.

**Comment by khrizo** [comment]
Hmm forgot to mention, I'm resending the ipn from (IPN) history.

Here is what I get on the request.POST, doesn't look right...
[12/Jul/2016 09:51:28] DEBUG [paypal.standard.ipn.views:41] --- (request.POST) ---
[12/Jul/2016 09:51:28] DEBUG [paypal.standard.ipn.views:42] <QueryDict: {u'\ufffdGA\x19)\x03': [u'']}>

[12/Jul/2016 09:51:28] DEBUG [paypal.standard.models:383] --- (request.body )-----
[12/Jul/2016 09:51:28] DEBUG [paypal.standard.models:384]  UÂ)

As far as the view being called:
Main urls.py
` url(r'^confirm/paypal/', include('paypal.standard.ipn.urls')) which goes to `

paypal urls.py
```
urlpatterns = [
    url(r'^$', views.ipn, name="paypal-ipn"),
]
```

**Comment by spookylukey** [comment]
You need to put in `repr(request.body)` not `request.body`, because otherwise you just get garbage as above.

Still, I think something else is wrong. This does not look like a real IPN from PayPal.

**Comment by spookylukey** [comment]
Closing due to lack of info and interest from the original reporter.
