### ISSUE TITLE
Compatibility with django 1.10?

### ISSUE THREAD

**Issue by llombard** [spookylukey/django-paypal#159]
Hi developpers,

has this code been tested with django 1.10? If not, is it in your plans?

Thanks for your reply (and your work),
Laurent

**Comment by spookylukey** [comment]
Yes, the master branch works with 1.10 and is tested against it (see tox.ini). I have not yet released a version with the required changes - I want to fix the test suite first - see #151 . If you install from GitHub you should be fine.

**Comment by spookylukey** [comment]
Version 0.3.3, just released, has Django 1.10 compat.
