### ISSUE TITLE
django signal not being fired

### ISSUE THREAD

**Issue by techietek** [spookylukey/django-paypal#161]
Hi,

I have been bashing my head against a wall and cant get the signal to fire, the records get stored in the database without a flag so a clean record yet the signal does not fire.

I am using sandbox to test this on paypal. 

I am running on django 1.9

signals.py file
```
import pdb, logging
from django.conf import settings
from paypal.standard.ipn.signals import valid_ipn_received, invalid_ipn_received
from django.dispatch import receiver

logger = logging.getLogger(__name__)


@receiver(valid_ipn_received)
@receiver(invalid_ipn_received)
def payment_notification(sender, **kwargs):
    ipn_obj = sender
    logger.info("payment_notification fired with following data:.")
```

apps.py file
```
from django.apps import AppConfig
class PaymentConfig(AppConfig):
    name = 'payment'
    verbose_name = 'Payments'  # optional
    #
    def ready(self):
        import donations.payment.signals
```

Your help will be a life saver at this stage.

**Comment by spookylukey** [comment]
What are you expecting the code above to do? Have you configured logging to print anything? If not, using a `print` statement/function would be an easier option.

Also, you could try a debugger, inserting it into the django-paypal code e.g. at https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/ipn/views.py#L24

You can use:

https://docs.python.org/2/library/pdb.html
https://github.com/rocky/python2-trepan
https://wiki.python.org/moin/PythonDebuggingTools

**Comment by techietek** [comment]
we can close this off there was a library I was importing on the signals.py file which broke the function, apologies for the churn.
