### ISSUE TITLE
How to style the PayPal window?

### ISSUE THREAD

**Issue by joaorodr84** [spookylukey/django-paypal#162]
I am trying to style the PayPal window for my online store.

I use Django 1.9 and the [django-paypal][1] app/plugin.

1) I want to hide the receiver e-mail address from the top of the window  
2) I want to display my logo at the top-left corner  
3) I want to display a detailed shopping cart, like shown in the image  

How can I achieve these steps using the options of the `PayPalPaymentsForm`?

I have tried this without success.

    def payment_paypal(request):
        paypal_dict = {
            "business": settings.PAYPAL_RECEIVER_EMAIL,
            "amount": price_convert(request.basket.total_value),
            "currency_code": "EUR",
            "item_name": request.order.order_number,
            "image_url": settings.PAYPAL_MY_LOGO_URL,
            "notify_url": settings.MAIN_URL + reverse('paypal-ipn'),
            "return_url": settings.MAIN_URL + reverse('payment_paypal_return'),
            "cancel_return": settings.MAIN_URL + reverse('checkout_payment'),
            "lc": "PT"
        }
        form = PayPalPaymentsForm(initial=paypal_dict)
        context = {"paypal_form": form}
        return render(request, "payment_paypal.html", context)

For the logo, besides `image_url`, I have also tried the `cpp_logo_image` and `cpp_header_image` options. Nothing worked.

![paypal details copy](https://cloud.githubusercontent.com/assets/5513952/20063987/fccfe3e4-a500-11e6-8646-76ff6a572205.PNG)

**Comment by spookylukey** [comment]
I just tried, and I have the same issue. I can confirm that the "image_url" gets passed through to PayPal, but it doesn't do anything. It would seem that PayPal docs are no longer correct - this is something to take up with their customer support, and is out of scope for django-paypal.

However, I wouldn't be surprised if they removed that feature - it seems incredibly open to abuse e.g. tricky someone into paying someone they didn't mean to pay.

**Comment by joaorodr84** [comment]
Thank you. :)

What about my issues 1 and 3?

1) I want to hide the receiver e-mail address from the top of the window  
3) I want to display a detailed shopping cart, like shown in the image

**Comment by spookylukey** [comment]
Sorry, these questions are out of scope for django-paypal - please refer to PayPal docs or PayPal support. This Django package is only about integrating with PayPal, if there is a problem with the integration please let us know, otherwise we can't help.

**Comment by joaorodr84** [comment]
Ok, thank you very much. :)
