### ISSUE TITLE
KeyError at /someurl ('True', 'buy')

### ISSUE THREAD

**Issue by stedotmartin** [spookylukey/django-paypal#165]
Hi, Firstly thanks for your project. 

I have ran into a little issue. 

When I create a `PayPalPaymentsForm` using the below code ( which I have copied from [the docs](http://django-paypal.readthedocs.io/en/stable/standard/ipn.html) I get a `KeyError` when calling `paypal_form.render()` this appears to coming from  `PayPalPaymentsForm.get_image()`

My code
--------

```
def someview(request):
    paypal_dict = {
        "business": "my@paypaladdress",
        "amount": settings.HOURLY_RATE,
        "currency_code": "GBP",
        "item_name": "Test item",
        "notify_url": "https://www.example.com" + reverse('paypal-ipn'),
        "return_url": "https://www.example.com",
        "cancel_return": "https://www.example.com",
    }
    paypal_form = PayPalPaymentsForm(initial=paypal_dict)

    context = {
        'paypal_form': paypal_form
    }
    return render(request, 'core/template.html', context)
```

Debugging
-----------
I have done some debugging but cannot understand why i'm getting a key error, 

```
def get_image(self):
        return {
            (True, self.SUBSCRIBE): SUBSCRIPTION_SANDBOX_IMAGE,
            (True, self.BUY): SANDBOX_IMAGE,
            (True, self.DONATE): DONATION_SANDBOX_IMAGE,
            (False, self.SUBSCRIBE): SUBSCRIPTION_IMAGE,
            (False, self.BUY): IMAGE,
            (False, self.DONATE): DONATION_IMAGE,
        }[self.test_mode(), self.button_type]
```

When I run my code and debug, self.test_mode() = 'True' and self.button_type = 'buy' so there should be a hit for the key in the dictionary object.  

Workaround
------------

To get round this at the moment, I am runtime patching `PayPalPaymentsForm.get_image()` like this, but would hope to understand the actual issue.

```
#views.py
from paypal.standard.conf import IMAGE

def new_get_image(self):
    return IMAGE

PayPalPaymentsForm.get_image = new_get_image
```

Thanks for any help.

**Comment by shapoglyk** [comment]
Got the same error when I want to override the url to button image.
```
def get_custom_image(self):
    return {
        (False, self.BUY): getattr(settings, "PAYPAL_IMAGE", "https://www.paypalobjects.com/webstatic/en_US/i/buttons/buy-logo-large.png")
    }[self.test_mode(), self.button_type]
```

**Comment by spookylukey** [comment]
It sounds like in your `settings.py` you have:

    TEST_MODE = 'True'

instead of:

    TEST_MODE = True


Please re-open if this is not the case and you can pinpoint an error in django-paypal.

**Comment by shapoglyk** [comment]
Yeah, thanks! And I came up with that there were no sense to override get_image() method to have custom image button. Just add PAYPAL_IMAGE to settings.

**Comment by stedotmartin** [comment]
I was pulling the TEST_MODE from an environmental variable so my `True` was actually coming through as a string and not a boolean. Will fix now. Thanks much appreciated.
