### ISSUE TITLE
New length=64 of "address_city"  is not reflected in migrations

### ISSUE THREAD

**Issue by Gera3dartist** [spookylukey/django-paypal#169]
standard/ipn/migrations/0001_initial.py has such entry:
('address_city', models.CharField(max_length=40, blank=True)),

in fact PayPalStandardBase has:
address_city = models.CharField(max_length=64, blank=True)

and there are no further migrations, which reflecting this change

**Comment by spookylukey** [comment]
`PayPalStandardBase` has `max_length=40`, and always has AFAICS:

https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/models.py#L99

Are you running from a modified copy perhaps?

I'm closing as this seems to be clearly incorrect. If there is something I'm missing, please re-open.
