### ISSUE TITLE
Sending 'rm' parameter from PayPalPaymentsForm

### ISSUE THREAD

**Issue by gusreyes01** [spookylukey/django-paypal#171]
I've noticed in some ocations paypal "return_url" is sent as a post. I've seend the docs and know there is an `rm` to use GET only.

How can I achieve this?

**Comment by spookylukey** [comment]
You should pass the required value of the `rm` parameter in the `initial` dict argument to `PayPalPaymentsForm` - see https://django-paypal.readthedocs.io/en/stable/standard/ipn.html

**Comment by gusreyes01** [comment]
@spookylukey Thanks, just yo be sure , would this work?:

```

    paypal_dict = {
        "business": "receiver_email@example.com",
        "amount": "10000000.00",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": "https://www.example.com" + reverse('paypal-ipn'),
        "return_url": "https://www.example.com/your-return-location/",
        "cancel_return": "https://www.example.com/your-cancel-location/",
        "custom": "Upgrade all users!",  # Custom command to correlate to some function later (optional),
        "rm": 1,
    }
```

**Comment by spookylukey** [comment]
I can't answer support requests like this - this is an issue tracker for bugs in django-paypal, not a support forum. Try it!

**Comment by gusreyes01** [comment]
@spookylukey will do, thanks!
