### ISSUE TITLE
Received IPN once, no longer receiving IPN in testing mode

### ISSUE THREAD

**Issue by goytia54** [spookylukey/django-paypal#172]
Hello,

I am developing a website and implementing the django-paypal API. I was able to get a POST to my notify_url once however when I tried to reproduce the result I could not do so on two different machines. 

I have followed your directions in your documentation page by making sure I am using ngrok to make my local machine visible as well as making the confirm_url csrf exempt as that was one hurdle I had to cross to initially get it to work.

Here is the current process I am using.

1) I run the the server locally using `python run manage.py runserver` in which I have the server running at `http://127.0.0.1:8000/`. 
2) I then run ngrok using the command `ngrock http 127.0.0.1:8000` to target the port I am running on.
3) I change the notify_url to the https url I get from ngrok , ex. (https://1420ef2e.ngrok.io/Notify) with the added reverse('paypal-ipn') on the end.
4) I update the url in which IPNs can be sent on the paypal website. 
5) I get to the point where I should see a post to the notify page but I don't see one.

I'm not sure what is causing the breakdown. I changed a couple of things around after getting the signal the first time as I felt they would not accept it however I believe the way I have implemented it is correct. I used the IPN simulator to make sure my notify page can recieve a post to the https://1420ef2e.ngrok.io/Notify for example, and I was successful.  I am quite perplexed on what might be occurring and feel that two others on stackoverflow might be having the same issue.

[http://stackoverflow.com/questions/42869542/django-paypal-unable-to-handle-notification-signal](http://stackoverflow.com/questions/42869542/django-paypal-unable-to-handle-notification-signal)
[http://stackoverflow.com/questions/42356166/signals-on-django-paypal-not-firing](http://stackoverflow.com/questions/42356166/signals-on-django-paypal-not-firing)
 
I'm not sure if this is a bug or a breakdown in my implementation. Any constructive insight on this would be great.

I have also attached files of views.py,  main urls.py, template urls.py, and the html page that has the button and the notify_url page.

Thanks

[possible_bug.zip](https://github.com/spookylukey/django-paypal/files/853418/possible_bug.zip)

**Comment by spookylukey** [comment]
Closed for reasons described in the README - https://github.com/spookylukey/django-paypal/#issue-tracker-and-support-requests

**Comment by spookylukey** [comment]
* You have commented out the include line in `urls.py`
* You have a file name `urls_main.py.py`
* Your notify_url is not as described in the docs - why are you adding `/Notify`?

Check the docs again, follow them carefully. Also, there is no way to know what is going on without a reproducible test project - you have just included a small set of files from your project which doesn't show me how it all fits together. However, please do not send a complete project again - I do not have resources for more support requests, I do this for free.
