### ISSUE TITLE
Obsolete PayPal documentation

### ISSUE THREAD

**Issue by TomSteck** [spookylukey/django-paypal#174]
Docs » PayPal Payments Standard » IPN/PDT variables

You provide link to **obsolete PayPal documentation**: https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNandPDTVariables/

In Django 1.10.5 errors related to obsolete data variables that are no longer returned in the IPN object are not raised or printed in the console by default. To do this I had to add this code in `my_app.__int__.py`

```
from django.conf import settings

class ExceptionLoggingMiddleware(object):
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        return response

    def process_exception(self, request, exception):
        if settings.DEBUG:
            print(exception.__class__.__name__)
            return None
```
and also add to project's `settings.py`:
```
MIDDLEWARE = [
    ...
    'my_project.my_app.ExceptionLoggingMiddleware',
]
```

**Comment by spookylukey** [comment]
I'll happily update the docs if you can provide a link to the correct docs.

I do not understand your second point at all.

1) if an exception occurs, it should crash the app, and normally this will be shown as a full stack trace in the returned page in development, and as a 500 error with a stack trace in the console. This happens in Django 1.10.5. If you are not seeing that, something strange is happening in your project. Do you have some other middleware that is silencing the errors?

2) I don't understand what you mean about obsolete data variables that are no longer returned in the IPN object.

For future reference, it is helpful if you can file distinct issues separately, thanks.

**Comment by TomSteck** [comment]
1. In `paypal.standard.ipn.models.py` you use send() function `valid_ipn_received.send(sender=self)`
> send() does not catch any exceptions raised by receivers; it simply allows errors to propagate. Thus not all receivers may be notified of a signal in the face of an error. [https://docs.djangoproject.com/en/1.10/topics/signals/](url)
Unfortunately errors related to invalid (obsolete) `ipn_obj` attributes are not raised / propagated

2. Unfortunately, I am not aware of any up-to-date PayPal documentation. First I followed the one that is referred in docs and therefore, I expected `ipn_obj` to return `amount` value but instead it returns `mc_gross` that is not documented in referred PayPal documentation.

**Comment by TomSteck** [comment]
Here is my MIDDLEWARE list. I added `ExceptionLoggingMiddleware` at the end so it should be run first as far I can understand, right?
```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'my_project.my_app.ExceptionLoggingMiddleware',
]
```

**Comment by spookylukey** [comment]
I'm afraid I still can't work out what you mean.

On the linked PayPal docs page, both `mc_gross` field and  `amount` field ARE present and documented - the latter being labelled as for recurring payments. Neither are listed as obsolete, though they have different purposes, and both are available on the `PayPalIPN` object, as documented here - http://django-paypal.readthedocs.io/en/stable/standard/variables.html which leads to the page you linked to.

Regarding the suppression of the exception, you are going to have to post the code you are using which is generating the exception, and how you are triggering the exception, including the GET/POST data from the request object (and how you are generating that request).

**Comment by TomSteck** [comment]
1. My error, I am sorry. First I was reading this page [Docs » PayPal Payments Standard » Using PayPal Standard IPN](http://django-paypal.readthedocs.io/en/stable/standard/ipn.html). In step number 3. there is a link to PayPal website that should provide "_a full list of variables that can be used in paypal_dict_".

> For a full list of variables that can be used in paypal_dict, see [PayPal HTML variables documentation](https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/).

...but there is no `mc_gross` field listed on that PayPal page. I guess this link should point to the page I mentioned in the first post (the same link you have just mentioned above). I can see now how I ended up using `amount` value when I first wrote my signal receiver function, as the best candidate reflecting amount paid by the buyer.

2. In my `valid_ipn_received` signal receiver function I was using `ipn_obj.amount` (instead of `ipn_obj.mc_gross`), and because PayPal sent only `mc_gross` value it was generating exception that was not raised or printed in the console. To replicate this behaviour just use variable that is not returned by IPN. After I changed `ipn_ob.amount` to `ipn_ob.mc_gross` value everything works fine.

**Comment by spookylukey** [comment]
On number 2, I can't replicate this.

If, in the signal handler function I attach, I access a real attribute on the IPN object for which no value was sent by PayPal, I get the default value as expected e.g.:

    print(ipn_obj.amount)

returns

    0

In some cases this default value could be `None`, I haven't checked them all.

If I access a genuinely non-existent field, then I get a stack trace on the console, as expected:

    print(ipn_obj.non_existent_field)

produces a stack trace that results in the following on the console:

    AttributeError: 'PayPalIPN' object has no attribute 'non_existent_field'   

I tested this using the PayPal IPN simulator + ngrok to test in my local development environment. In addition everything else I know about how this works makes it very unlikely that django-paypal works incorrectly here. It's possible you have some strange setup that is silencing errors some how, which I'd recommend you investigate, because otherwise you could have a hard time debugging other things.

The only other thing I can think of is that you are talking about using the console when DEBUG=False In that case no stack trace is printed - this is expected behaviour of Django if DEBUG is False, nothing to do with django-paypal. For development, it's most helpful if you have DEBUG = True, and you shouldn't be using the Django development server at all in production, it's not safe.

I'm going to close this now, I think there must be some confusion. If you can provide enough information for me to pinpoint an error in django-paypal, please re-open.

**Comment by spookylukey** [comment]
I added a note about the PayPal docs seeing as they easily confused, and also badly named (e.g. you pass in `amount` and end up with `mc_gross`, while the returned `amount` means something different).
