### ISSUE TITLE
Method make_secrete in paypal/standard/helpers.py not compatible with python 3

### ISSUE THREAD

**Issue by guzvin** [spookylukey/django-paypal#177]
The method make_secret in paypal/standard/helpers.py uses type unicode which does not exist in Python 3, resulting in NameError - name 'unicode' is not defined.

**Comment by spookylukey** [comment]
Thanks for the report.

As I don't use that code myself, I'm waiting for someone who does to supply the appropriate tests and fixes, as described in the project status section in the README - https://github.com/spookylukey/django-paypal#project-status

If you can provide a patch, complete with tests for the functionality, it would be gladly accepted.

**Comment by Nelestya** [comment]
Noramally is patched.
https://github.com/spookylukey/django-paypal/pull/198

I have use this:
https://stackoverflow.com/questions/6812031/how-to-make-unicode-string-with-python3

cordially
