### ISSUE TITLE
PayPal sandox not responding?

### ISSUE THREAD

**Issue by moreplavec** [spookylukey/django-paypal#178]
I tried to use **Django Paypal** via **Django by Example** book. All went OK and example is same as examples over the net. But while in test mode, when redirected to Paypal sandbox, nothing happens. I get blank page and nothing more. Looks like wrong URL or calling? If i turn off testing and go live, payment works as expected.

Django: 1.11.2
Python: 3.5.2
Django-PayPal: 0.3.6

**Comment by spookylukey** [comment]
I get the same thing. As far as I can see, this is a PayPal issue - looks like they broke their sandbox. You should contact their support.

Another recent report of the same thing - https://stackoverflow.com/questions/44736319/sandbox-paypal-white-blank-screen-nothing-happen

**Comment by moreplavec** [comment]
Aha, thanks for info!
