### ISSUE TITLE
i18n translation support on PaymentForm ?

### ISSUE THREAD

**Issue by afranche** [spookylukey/django-paypal#181]
Hello there.

I'm currently in charge of building a service which would require other languages than English and I came across django-paypal when we needed to add shopping carts.

The issue there is that PaymentForm included in pro.forms isn't translated at all.
![image](https://user-images.githubusercontent.com/11685232/27964539-f0449ae2-6338-11e7-98ab-27fb3dfa581b.png)

I just came across searching for Issues or PR that mentioned any translation support using gettext but nothing here.

Is it planned ? I can get myself to do a PR if needed. Also, is any changes on the currency possible ? I didn't completely checked the codebase.

Thanks.

**Comment by spookylukey** [comment]
Fixed now, thanks for the PR.
