### ISSUE TITLE
Encrypted buttons should be annotated as not supported on Python 3 at the moment

### ISSUE THREAD

**Issue by afranche** [spookylukey/django-paypal#183]
Since the module's Encrypted buttons are relying on M2Crypto, it should be mentioned that it will not work on Python 3: [Related Issue on M2Crypto's GitLab Pages](https://gitlab.com/m2crypto/m2crypto/issues/114).

**Comment by afranche** [comment]
I updated the doc in purpose: #184

**Comment by spookylukey** [comment]
Fixed via #184
