### ISSUE TITLE
Where to put notify view function?

### ISSUE THREAD

**Issue by taylorconsulting** [spookylukey/django-paypal#186]
In the documentation it states that a function called `show_me_the_money(sender, **kwargs)` should be added to the project in order to handle the POST request sent by PayPal on completion of payment. However, the documentation fails to describe where that function should be placed. Should it be placed in the views.py file of the current project, or should there be another python file created just for that function?

**Comment by spookylukey** [comment]
The documentation doesn't mention it because you may put it wherever you like that makes sense for your project. Please see the Django docs in signals - https://docs.djangoproject.com/en/dev/topics/signals/ . There is a section "Where should this code live?"

Hope that helps.
