### ISSUE TITLE
Documentation: Remove hardcoded url from view

### ISSUE THREAD

**Issue by vassilisw** [spookylukey/django-paypal#188]
This applies to documentation...

in our views.py, implementing the `view_that_asks_for_money(request)` instead of
`"notify_url": "https://www.example.com" + reverse('paypal-ipn'),`
we can have
`"notify_url": request.build_absolute_uri(reverse('paypal-ipn')),`

**Comment by spookylukey** [comment]
Thanks for the suggestion, done now
