### ISSUE TITLE
Using both PDT and IPN toghether

### ISSUE THREAD

**Issue by sandroden** [spookylukey/django-paypal#192]
Hi, I'm just starting to setup my first Paypal site. While choosing which method best suits my need between PDT and IPN I [found people state they use both ](https://stackoverflow.com/questions/2836779/ipn-vs-pdt-in-paypal/2836831) in the same application, IPN as it's safer (retries several time to send the message) and PDT to prevent the possibility the user returns to the wesite before the message arrived.

I'd like to know if this is possible with django-paypal.

Thanks in advance
Sandro

**Comment by spookylukey** [comment]
Yes, it's possible. Just take care that you don't process the payment twice.
