### ISSUE TITLE
Django 1.11 and python 3.6

### ISSUE THREAD

**Issue by delitamakanda** [spookylukey/django-paypal#193]
```
Forbidden (CSRF cookie not set.): /paypal/
[22/Oct/2017 10:02:25] "POST /paypal/ HTTP/1.1" 403 2857
```
I'm stuck with this problem. How I can solve it properly because signals valid_ipn_received.connect cannot be trigger. Thank for your help

**Comment by dhontecillas** [comment]
You should check your ```urls.py``` file, do you have this set ?

```python
url(r'^paypal/', include('paypal.standard.ipn.urls'))
```
[paypal.standard.ipn.views](https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/ipn/views.py) are already decorated with ```csrf_exempt```, and you should not have this problem.

**Comment by delitamakanda** [comment]
Thank you. Finally my problem was due to  migration files. Work good now !
