### ISSUE TITLE
Integration with paypal pro

### ISSUE THREAD

**Issue by luca120289** [spookylukey/django-paypal#197]
Hi,
I'm using Django 1.11.9 with Python3 and I'm trying to integrate the payments with paypal pro.

I followed the guide here: https://django-paypal.readthedocs.io/en/stable/pro/index.html
but when I click on the button "Pay up" the page simply reload and nothing else happen. I can't get the confirmation page.

I haven't any error in console at all so I can't understand if there's any problem with my code.

I followed the exact instructions on the guide.

Let me know if you need more information or code.

**Comment by spookylukey** [comment]
Without seeing your code, it's of course impossible for me to work out what is wrong. However, I do not provide that level of support for django-paypal - you will need to work out what is wrong yourself.
