### ISSUE TITLE
ipn_obj.id returning none in helpers duplicate_txn_id causing duplicate txn_id flag

### ISSUE THREAD

**Issue by EthanTurek** [spookylukey/django-paypal#203]
This is causing all but the very 1st entry to flag ```Duplicate txn_id```
Is it safe to comment out ```.exclude(id=ipn_obj.id)```? Everything seems to function just fine w/o it.

Python: 3.6.5rc1
Django: 2.1
Backend: Mongodb

```python
def duplicate_txn_id(ipn_obj):
    print(dir(ipn_obj)) # ipn_obj.id exists here
    print(type(ipn_obj.id)) # None Class
    print(ipn_obj.id) # None
    similars = (ipn_obj.__class__._default_manager
                .filter(txn_id=ipn_obj.txn_id)
                .exclude(id=ipn_obj.id) # ipn_obj.id does get set in the database though???
                .exclude(flag=True)
                .order_by('-created_at')[:1])

    if len(similars) > 0:
        return similars[0].payment_status == ipn_obj.payment_status

    return False
```

**Comment by spookylukey** [comment]
I'm afraid that I have no expertise in MongoDB. Django's ORM is an Object **Relational** Mapper, and Mongo is **not a relational database**, so you are really going to make life extremely difficult for yourself. My hunch is that it is *not* safe to change that code, and that you have a serious bug in whatever MongoDB-Django backend you are using, which could be doing all kinds of other bad things too, who knows. But I'm afraid I can't provide any further support.
