### ISSUE TITLE
Migration being created automatically in Django 2.1

### ISSUE THREAD

**Issue by guilhermej** [spookylukey/django-paypal#206]
I'm trying to use Django-paypal with `Django 2.1.1` and `Python 3.5`.

But when I run makemigrations Django automatically creates a new migration file `paypal/standard/ipn/migrations/0008_auto_<datetime>.py`

The file's content:
``` python
# Generated by Django 2.1.1 on 2018-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0007_auto_20160219_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalipn',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='test_ipn',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
```

This causes problems because when you move to the production environment migrations after that require such a file, which obviously does not exist in the production virtualenv.

In the tests I did the module works normally in Django 2.1, but such migration is lacking.

**Comment by spookylukey** [comment]
Fixed now in master
