### ISSUE TITLE
Receiving 2 IPN for subscription.

### ISSUE THREAD

**Issue by noisytoken** [spookylukey/django-paypal#207]
I am testing PayPal standard with subscription using a sandbox account.

After successful subscription I always receive 2 IPNs from PayPal. One is of type `subscr_payment` and the other is of type `subscr_signup`. The former contains information regarding the transaction and latter contains information about the recurring payment.

This is how they look in the Django admin.

![image](https://user-images.githubusercontent.com/6175606/47956310-7db0eb80-dfc8-11e8-922a-2e28cb6b860e.png)

Is this normal? or Am I doing something wrong?

**Comment by spookylukey** [comment]
I haven't used subscription features myself, so I'm afraid I can't comment. According to [this StackOverflow question](https://stackoverflow.com/questions/1061683/subscriptions-with-paypal-ipn#1195246) it sounds normal. For further questions you'll need to look at PayPal docs for this.

**Comment by noisytoken** [comment]
Yes, that's how it works.

Here is the link to PayPal docs which describes different types of transaction.

https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/#

Thanks
