### ISSUE TITLE
TypeError at /payment-url/

### ISSUE THREAD

**Issue by 0rski** [spookylukey/django-paypal#208]
Hey, I'm getting this error:
TypeError at /payment-url/
'bool' object is not callable

/anaconda3/envs/myDjangoEnv/lib/python3.7/site-packages/paypal/pro/models.py in init, line 105

line 105:  if hasattr(request, "user") and request.user.is_authenticated(): 

any idea? :) thanks.

**Comment by spookylukey** [comment]
This is fixed on master, not sure when I'll get round to a release.
