### ISSUE TITLE
Using with Django 2.1.7 django says it needs to create another migration file

### ISSUE THREAD

**Issue by BITSOLVER** [spookylukey/django-paypal#210]
I have django-paypal 0.5.0 installed with pip.  It has started saying that django needs to create another migration file.  If I run the following I get:

`django-admin makemigrations --dry-run

Migrations for 'ipn':
  /Users/steven/.virtualenvs/bookingsmanager/lib/python3.6/site-packages/paypal/standard/ipn/migrations/0008_auto_20190321_1204.py
    - Alter field flag on paypalipn
    - Alter field test_ipn on paypalipn

Process finished with exit code 0`

I'm running python 3.6.5

The following migrations are on my system:

`ls -l /Users/steven/.virtualenvs/bookingsmanager/lib/python3.6/site-packages/paypal/standard/ipn/migrations/ 
total 80
-rw-r--r--   1 steven  staff  10845 Aug 14  2018 0001_initial.py
-rw-r--r--   1 steven  staff    446 Aug 14  2018 0002_paypalipn_mp_id.py
-rw-r--r--   1 steven  staff    421 Aug 14  2018 0003_auto_20141117_1647.py
-rw-r--r--   1 steven  staff   4944 Aug 14  2018 0004_auto_20150612_1826.py
-rw-r--r--   1 steven  staff    596 Aug 14  2018 0005_auto_20151217_0948.py
-rw-r--r--   1 steven  staff    601 Aug 14  2018 0006_auto_20160108_1112.py
-rw-r--r--   1 steven  staff    786 Aug 14  2018 0007_auto_20160219_1135.py
-rw-r--r--   1 steven  staff      0 Aug 14  2018 __init__.py
`

I'm also using Postgres 9.6.10

Do we need a new release to add migrations for the project?

Steve

**Comment by spookylukey** [comment]
This was addressed in #206 on master - I've done a new release now, v1.0.0 on PyPI.

**Comment by BITSOLVER** [comment]
Thanks for the release, Steve.

**Comment by boskicthebrain** [comment]
I just figured out that I did make that phantom migration which is making problems for me now, because I have conflicting migrations after I want to upgrade.
```
Creating test database for alias 'default'...
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0008_auto_20181128_1032, 0008_auto_20210922_2228 in ipn).
To fix them run 'python manage.py makemigrations --merge'
```
No I don't know where to find that wrong migration or rather how to revert it in order to be able to migrate the DB schema properly. This has become kind of an issue, because the library has become buggy recently, and I recon it is because the library version is too old. I thought it wouldn't hurt if I upgraded first and then researched further.

Does anyone have any piece of advice?

**Comment by spookylukey** [comment]
Probably what you want to do is
1. get rid of the extra migration file you created
2. manually edit the `django_migrations` table that stores your migration history to make it match what it should be.

I'm afraid I can't provide any more help than that.
