### ISSUE TITLE
Very minor issue with generated HTML

### ISSUE THREAD

**Issue by vorwrath** [spookylukey/django-paypal#212]
The buy button HTML inside the form django-paypal generates is something like `<input type="image" src="path_to_button_image.png" border="0" name="submit" alt="Buy it Now" />`

When I ran a page including the form through the W3C validator (https://validator.w3.org/nu/) it complained about putting the border attribute on an input element, so I think that should probably be removed.

**Comment by spookylukey** [comment]
It looks like `border="0"` is the default for image input fields in browsers these days, so it is safe to remove. I'll gladly accept a patch to remove it, tests etc. not needed.
