### ISSUE TITLE
IPN signal cannot be received, error code 403, receiving address /paypal/

### ISSUE THREAD

**Issue by YuanSyun** [spookylukey/django-paypal#213]
Dear developer 

I tested the Paypal IPN signal using Django 2.0.1 and django-paypal 1.0.0, but the server would get 403 access denied. The notification link I set is 
`‘notify_url’: ‘http://{}{}’.format(host, reverse(‘paypal-ipn’))`. 

I checked **paypal/standard/ipn/urls.py** and found that Django couldn’t read 
`url(r’^$’, views.ipn, name="paypal-ipn")`
I changed it to 
`url(r’^ipn/$’, views.ipn, name="paypal-ipn")`
, and finally receive the IPN signal.

I don't know if this is a problem with my environment. If anyone has a similar problem, here is a solution.

**Comment by spookylukey** [comment]
It's possible there is a problem with the way you are including the urls - did you do it the same way as described in https://django-paypal.readthedocs.io/en/stable/standard/ipn.html ?

**Comment by YuanSyun** [comment]
Hi spookylucky, thank you for responding to this issue.

Yes, I had follow [it](https://django-paypal.readthedocs.io/en/stable/standard/ipn.html) and I also refer to [this teaching website](https://overiq.com/django-paypal-integration-with-django-paypal/).
For clarity on my configuration. Here is my environment:
- Python version is 3.6.5.
- The setting.py file
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart.apps.CartConfig',
    'shop.apps.ShopConfig',
    'orders.apps.OrdersConfig',
    'paypal.standard.ipn',
    'payment',
    'rest_framework',
]
...

# django-paypal settings
PAYPAL_RECEIVER_EMAIL = 'sb-xadzg*****@business.example.com'
PAYPAL_TEST = True
```
- The main urls.py setting
```
From django.contrib import admin
From django.urls import path, include
From django.conf import settings
From django.conf.urls.static import static
From rest_framework.routers import DefaultRouter
From shop import views

Router = DefaultRouter()
Router.register(r'shop', views.ShopViewSet, base_name='Product')

Urlpatterns = [
                Path('admin/', admin.site.urls),
                Path('cart', include('cart.urls')),
                Path('orders/', include('orders.urls')),
                Path('', include('shop.urls')),
                Path('payment/', include(('payment.urls', 'payment'))),
                Path('paypal/', include('paypal.standard.ipn.urls')),
                Path('api/', include(router.urls))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by spookylukey** [comment]
Your configuration looks correct. But I know the docs I also correct because I follow them in my own project and it works, so I don't know what the problem can be. I'm going to have to close for now because I'm not able to debug further. 

Thanks!
