### ISSUE TITLE
Occasional invalid postbacks: 400 Bad Request

### ISSUE THREAD

**Issue by vmspike** [spookylukey/django-paypal#216]
Starts from July I occasionally get flagged payments with invalid postback.
flag_info:
```
Invalid postback. (<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
)
```
but on PayPal side it's valid payment.

Do you know what can be wrong with them and how to avoid?
Let me know please if you need some additional info.

django-paypal version is 0.5.0, django 2.1

**Comment by newearthmartin** [comment]
Same as https://github.com/spookylukey/django-paypal/issues/117

**Comment by spookylukey** [comment]
As far as I can tell, this is a PayPal bug, it's either the same as #117 or the best we can do is the same solution as we're now looking at in #117 - so I'm closing in favour of that bug.
