### ISSUE TITLE
Subscription with django-paypal using IPN broken?

### ISSUE THREAD

**Issue by cedricwebisoft** [spookylukey/django-paypal#220]
Hi!

I already have a paypal integration on my website with django-paypal IPN that work well with one-time payment of products.

I now try to add subscription to my website with django-paypal ipn and subscriptions options.

I know all my settings are right as the one-time payment work.
There is what I set as `initial` to `PayPalPaymentsForm`

    {
        'cmd': '_xclick-subscriptions', 
        'a3': '109.99', 
        'p3': '1', 
        't3': 'Y', 
        'src': '1', 
        'sra': '1', 
        'no_note': '1', 
        'business': 'my@email.com', 
        'currency_code': 'CAD', 
        'invoice': '3e57', 
        'notify_url': 'my_domiain.com/paypal/', 
        'return': 'my_domain.com/shop/purchases/', 
        'cancel_return': 'my_domain.com/shop/cart/', 
        'custom': '{}', 
        'item_name': 'Beginner subscription'
    }

I am redirected to paypal with informations about the subscription and a button to pay with paypal or credit card, but when I click on either button, I got the message

`Things don't appear to be working at the moment. Please try again later.`

The django-paypal code also has a warn_untested method on `PayPalPaymentsForm.is_subscription` so I wonder if something has changed or is broken maybe? Or is there something to do in paypal to set subscription?

Theres no log anywhere, nothing that point me to the possible cause of the error so I am pretty lost. 

Thanks for the help.

**Comment by spookylukey** [comment]
It's possible that it is untested or broken. I'm afraid I won't be able to answer these questions - you'll need to look at the PayPal docs and see what is needed. If it turns out that django-paypal needs fixing, or its docs need improving, please do submit an issue, but I won't be able to provide any support on this. Sorry!

**Comment by nikijoe** [comment]
Hai. I had my local testing site working with ipn in sandbox and everything was fine. After 28/04/2020 paypal is telling about some updates and  the same message "Things don't appear to be working at the moment. Please try again later." comes. Paying card (testing) is not verified with CCV. But if you change the paypal_dict "business" to NVP user id it says money transferred and receipt send. But you cannot view that transfer in your sandbox account as you do not have that account. Then i tried pro, and it says it is not available for testing. Hope it works fine with real transfers.

**Comment by tochimclaren** [comment]
Hello, I got the same message trying to integrate django-paypal with subscrption for my website, I'm getting this error after succesful redirect to paypal website.

Things don't appear to be working at the moment. Please try again later.
