### ISSUE TITLE
Sandbox Payment goes through but IPN Signal is not received...

### ISSUE THREAD

**Issue by arcticruno** [spookylukey/django-paypal#222]
Hey my website is live. I am able to make live payments, where I receive the Ipn signal. But when I set it back to sandbox.paypal account. The payment is going through, but I cant receive the signal in my signals.py. Instead I get an 502 Proxy Error. Does anyone know what is going on?
I found that there was an IPN incident from 30.1. - 7.2. on sandbox paypal account...

**Comment by spookylukey** [comment]
Closing because this is a support request, sorry I can't help.
