### ISSUE TITLE
PayPalPaymentsForm renders value in DOM 

### ISSUE THREAD

**Issue by KalobTaulien** [spookylukey/django-paypal#224]
Hey there,

There's a problem with the button when using `{{ form.render }}` — the purchase value is editable through the DOM. The amount you want to pay can be changed to anything you want. Most often it's set to `0.01` to buy anything for one penny. 

![image](https://user-images.githubusercontent.com/4743971/75116544-bb56df00-5626-11ea-8943-eb6be95b9d43.png)

I know this is technically a PayPal problem, but they have other solutions around this that I think should be highlighted more in the docs.

**Comment by newearthmartin** [comment]
What you are pointing at is true. However, nothing prevents you from adding
a check for the amount when you receive notice of the payment via IPN to
see if the user tried to change this number.

Also, this is addressed in the new js paypal button, in which you call
directly paypal apis to present the button. So the button comes directly
from paypal itself. This is not implemented in django-paypal yet. I created
an issue to start discussing implementation.
https://github.com/spookylukey/django-paypal/issues/221

**Comment by spookylukey** [comment]
There are clear warnings here that you need to check the data received:

https://django-paypal.readthedocs.io/en/stable/standard/ipn.html

For example, under point 5, and in the example code.

Are you looking for something more than that? Perhaps it could be clearer in some way? I'm open to suggestions.

**Comment by newearthmartin** [comment]
Ah! I didn't know it was a GET form. If so, we don't need to put the form
in the template. We could just have a button that goes to a Django view and
this view redirects to paypal with all the data, without the user being
able to tamper the form.

**Comment by spookylukey** [comment]
If you do a redirect, the user will still be able to tamper with data (they can change the URL you direct them to). The correct way to do it is to ensure the data is what you expect at the end, without assuming you have prevented tampering.

I'm closing this ticket now, thanks.
