### ISSUE TITLE
django-paypal ipn server-side only, is it possible ?

### ISSUE THREAD

**Issue by Chipop** [spookylukey/django-paypal#227]
Hello in my project I wanted to implement only server-side PayPal and I made this code

```
def checkout_paypal(request, pk):

    order = get_object_or_404(Order, pk=pk)

    # What you want the button to do.
    paypal_dict = {
        "business": settings.PAYPAL_MERCHANT_EMAIL,
        "amount": order.get_total_price_usd(),
        "item_name": order.get_order_items_name(),
        "invoice": "#" + order.reference,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('payment:checkout_success', kwargs={'pk': pk, })),
        "cancel_return": request.build_absolute_uri(reverse('payment:checkout_cancel', kwargs={'pk': pk, })),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
        "cmd":"_xclick",
        "charset": "utf-8",
        "currency_code": "USD",
        "no_shipping": "1",
    }
    # Create the instance.
    # form = PayPalPaymentsForm(initial=paypal_dict) # I don't need this 
    # context = {"form": form} # I don't need this 

    paypal_url = "https://www.sandbox.paypal.com/cgi-bin/webscr"

    data = urllib.parse.urlencode(paypal_dict)
    data = data.encode('ascii')
    user_agent = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)'
    headers = {'User-Agent': user_agent}
    req = urllib.request.Request(paypal_url, data,headers)
    with urllib.request.urlopen(req) as response:
        try:
            return redirect(response.url)
        except:
            return render(request, "payment/checkout/checkout_error.html", context)
```

I submit PayPal form directly on the view using urllib to post data. And I redirect the user to the PayPal website payment directly, skipping that PayPal button because of my specific need on my project.

Do you think it is ok to use this approach or there will be some issues that I didn't notice ? Thanks

**Comment by spookylukey** [comment]
If you are using a redirect to send the user to PayPal, you are putting the data in GET parameters instead of putting in POST parameters, which is not standard and potentially has issues. I'd recommend an auto-submitting button - it can be invisible, but it should do a POST to PayPal, not GET.

I didn't understand the bit about submitting data to the view using urllib, I don't know why that would be necessary or which view your are talking about.

**Comment by Chipop** [comment]
I am not redirecting (using GET) to the URL in <form action="..." method="post" ...
which is 

`https://www.sandbox.paypal.com/cgi-bin/webscr. `

I am posting to it using POST in this line : 

`req = urllib.request.Request(paypal_url, data,headers)`


and then I get response from PayPal : 

`return redirect(response.url)`

and the response contains  this URL : 

`https://www.sandbox.paypal.com/webapps/hermes?token=2F100927MF229134D&useraction=commit&mfid=1590850374211_b61a8b188ab61`

PayPal redirects us to this new url for payment, which contain get parameters with a unique token, and this url can be accessed using GET.

This latter url is  the true payment url that can be accessed with GET ( can be redirected to ) and can lead us to this payment page 

I even copied this url in another browser and still give me the payment page, so I noticed that it can be used programatically.

![jdjd](https://user-images.githubusercontent.com/15788435/83331476-9fe71a00-a28e-11ea-8a79-44ca0e902820.png)

What  do you think ?

**Comment by spookylukey** [comment]
What can you do with that URL? You can't log in, because you don't have the user's credentials (and it would be a very idea or impossible or illegal to get them). The only thing you can do is to send the user to this URL, which is exactly the same as what happened before. Except the normal way is the way PayPal supports.

**Comment by Chipop** [comment]
Yes I send them to that URL and its for them to enter their credential, but the only positive thing I see here is that they can't change the button hidden inputs.

It works perfectly on development but I don't know if it will work on production. If not I will use an auto-submitting button, thanks for mentioning that.

**Comment by spookylukey** [comment]
You really shouldn't do it any other way than how the PayPal docs say, there is no guarantee that other methods will work or carry on working. There is no real advantage to stopping people from changing hidden button inputs because you must checking values when they come in anyway.
