### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /paypal_notify/   

### ISSUE THREAD

**Issue by jaytifd** [spookylukey/django-paypal#233]
I was getting intermittent timeouts from the postback process.  I suspect my provider (Dreamhost) has blocked or throttled requests to www.paypal.com.

However, I noticed that on the paypal site, it recommends [setting the postback ](https://developer.paypal.com/docs/api-basics/notifications/ipn/IPNImplementation/)as follows:

```
Send response messages back to PayPal:

    https://ipnpb.sandbox.paypal.com/cgi-bin/webscr (for Sandbox IPNs)
    https://ipnpb.paypal.com/cgi-bin/webscr (for live IPNs)


```
I configured  conf.py to point to those urls and no more timeouts!

So you might consider updating the postback urls to match PayPal's recommendations:

POSTBACK_ENDPOINT = "https://ipnpb.paypal.com/cgi-bin/webscr"
SANDBOX_POSTBACK_ENDPOINT = "https://ipnpb.sandbox.paypal.com/cgi-bin/webscr"

```
Error message from django:
HTTPSConnectionPool(host='www.paypal.com', port=443): Max retries exceeded with url: /cgi-bin/webscr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x34e861dd8d0>: Failed to establish a new
connection: [Errno 110] Connection timed out',))

```

**Comment by spookylukey** [comment]
Thanks for the report!
