### ISSUE TITLE
New PayPal API

### ISSUE THREAD

**Issue by nawtybean** [spookylukey/django-paypal#235]
Hi There, I noticed that PayPal is upgrading their API, will these changes affect Django PayPal in anyway? if so, will there be a new django-paypal release coming out to facilitate these PayPal changes?

**Comment by spookylukey** [comment]
I'm afraid I don't know what you are referring to. If you are talking about a new API that PayPal is bringing out, the answer to your questions are already in the README  - https://github.com/spookylukey/django-paypal

**Comment by newearthmartin** [comment]
I think he means this https://github.com/spookylukey/django-paypal/issues/221
