### ISSUE TITLE
PayPalPaymentsForm action url

### ISSUE THREAD

**Issue by LukaRiba** [spookylukey/django-paypal#237]
Hello, after updation of POSTBACK_ENDPOINT/SANDBOX_POSTBACK_ENDPOINT urls to ipnpb.paypal.com/ipnpb.sandbox.paypal.com instead of www.paypal.com/www.sandbox.paypal.com ([commit ](https://github.com/spookylukey/django-paypal/commit/c611a6223fa5f272383d6ab5f49eb30fd70512a9)) PayPalPaymentsForm is rendered with these as action url so instead of bieng redirected to Paypal login we get "encrypted_cross_dispatch=<some_long_hash>" as a response. I changed form action url back to www and that solved the issue, as suggested [here](https://www.paypal-community.com/t5/PayPal-Payments-Standard/ipnpb-paypal-com-error-encrypted-cross-dispatch/td-p/1193332). Maybe separated setting for action url can be added along POSTBACK_ENDPOINTs ? Im still using only sandbox account

**Comment by spookylukey** [comment]
Thanks for the report. It looks like we need a separate URL for this, as you suggest.
