### ISSUE TITLE
Listing the payments

### ISSUE THREAD

**Issue by abolix** [spookylukey/django-paypal#240]
I'm trying to list all of the PayPal IPNs transactions in my website 
so right now i'm using this code :
`transactions = PayPalIPN.objects.all().exclude(payment_status__exact='').exclude(flag__exact=True).order_by('-payment_date') `

there is few problems with this code :

- sometimes I have 2 transactions with same Transaction id but different status (one 'Reversed' and one (Canceled_Reversal) and i just want to show the Canceled_Reversal )
- sometimes flag is True and flag info says "Invalid postback. (<html> <body> Fatal Failure <br> </body> </html> )" but it's completed

how can I solve these and show all of transactions clearly ?

**Comment by spookylukey** [comment]
I'm sorry, that is a general Django question, you should ask on a Django users forum, this is an issue tracker for bugs in django-paypal.
