### ISSUE TITLE
Paying directly with a debit card

### ISSUE THREAD

**Issue by mzuzic** [spookylukey/django-paypal#248]
Hi, is it possible to enable users to pay directly using a credit card, not needing to create a Paypal account? 

I'm rendering them a form for subscription payments. As we can see on the screenshot bellow, they need to login to Paypal first.

![image](https://user-images.githubusercontent.com/41955384/148256516-19bd487d-52a5-4504-ab2a-e0eb5c621535.png)

**Comment by spookylukey** [comment]
This is a PayPal question, not a django-paypal thing. Probably this is relevant:
https://www.paypal.com/us/smarthelp/article/how-do-i-accept-credit-cards-with-checkout-using-the-guest-checkout-option-faq3226
