### ISSUE TITLE
How to use this sdk in django-rest-framework

### ISSUE THREAD

**Issue by PeiPeiWow** [spookylukey/django-paypal#279]
I want to use this sdk in django-rest-framework, my frontend is written by react,and I want to use this SDK as a backend, how to do, please help.

**Comment by spookylukey** [comment]
I'm afraid this isn't a support channel, all I can do is suggest you read the documentation. This package is not really designed to be used with an SPA fronted, you'll need to do the front end parts yourself.

**Comment by PeiPeiWow** [comment]
> I'm afraid this isn't a support channel, all I can do is suggest you read the documentation. This package is not really designed to be used with an SPA fronted, you'll need to do the front end parts yourself.

thank you
