### ISSUE TITLE
Outdated package and documentation

### ISSUE THREAD

**Issue by aquilarubra** [spookylukey/django-paypal#288]
Hello, please update the pip package and the documentation.

Package: https://pypi.org/project/django-paypal/
By default, pip installs an outdated version. For example, get_html_submit_element is not even triggered and therefore cannot be overridden.

Documentation: https://django-paypal.readthedocs.io/en/latest/install.html
This line is incorrect and gives an error: pip install git://github.com/spookylukey/django-paypal.git#egg=django-paypal
It should be: pip install git+https://github.com/spookylukey/django-paypal.git

It would also be helpful if there would be more extended documentation. For example, how to use a donation button (please, notice that the alt text still remains "Buy it", which is wrong), etc.

**Comment by aquilarubra** [comment]
Adding this. In this page, https://django-paypal.readthedocs.io/en/latest/settings.html, PAYPAL_DONATE_BUTTON_IMAGE is wrong. It should be PAYPAL_DONATION_BUTTON_IMAGE

**Comment by spookylukey** [comment]
OK, version 2.1 released with docs fixes.

> It would also be helpful if there would be more extended documentation. For example, how to use a donation button (please, notice that the alt text still remains "Buy it", which is wrong), etc.

This is a really open ended item which needs it's own issue. As noted, this project is in maintenance mode, and the payment methods supported here are really old.
