### ISSUE TITLE
Missing CSRF Token in ipn.html Template

### ISSUE THREAD

**Issue by mohammedeloon** [spookylukey/django-paypal#292]
While reviewing the code for the PayPal package, I found that the **ipn.html** template located at **paypal/standard/ipn/templates/ipn/ipn.html** is missing the CSRF token. The CSRF token is a crucial security measure to prevent Cross-Site Request Forgery (CSRF) attacks.

**Current Code:**
```
<form action="" method="post">
    <table>
        {{ form.as_p }}
        <tr>
            <td colspan="2" align="right">
                <input type="submit"/>
            </td>
        </tr>
    </table>
</form>
```

**Suggested Fix:**

```
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_p }}
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Submit"/>
            </td>
        </tr>
    </table>
</form>

```

**Comment by spookylukey** [comment]
The `ipn.html` file you have found appears to be unused, it should be removed entirely.

**Comment by mohammedeloon** [comment]
Yes, I have checked dependencies to the ipn .html file. It is not used. So the best thing to do is to delete the file to keep the package nice and need and avoid confusion.

**Comment by spookylukey** [comment]
Thanks, I've fixed this now by deleting the file.
