### ISSUE TITLE
Cannot post to express checkout view

### ISSUE THREAD

**Issue by tarkatronic** [spookylukey/django-paypal#41]
I have a use case where I would like to be able to post data to my checkout (specifically a shopping cart id). Additionally, I would prefer to use a post operation, to prevent any possible xss on my cart page.

Is there a technical reason why the PayPalPro class differentiates between methods? If not, I would like to supply a fix to remove this restriction.

**Comment by spookylukey** [comment]
Closing for reasons described in the project README
