### ISSUE TITLE
Express checkout endpoints should be accessible as settings

### ISSUE THREAD

**Issue by tarkatronic** [spookylukey/django-paypal#53]
I'm approaching a point in my PayPal implementation where it almost makes sense to create my entire own view, forgoing paypal.pro.views.PayPalPro entirely. However, the endpoints are only set in paypal.pro.views and the logic to choose between them is inside the PayPalPro view.

Ideally, I would like to be able to retrieve settings.PAYPAL_EC_ENDPOINT which would choose the appropriate (sandbox/live) endpoint, as well as PAYPAL_EC_LIVE_ENDPOINT or PAYPAL_EC_SANDBOX_ENDPOINT.

Something like this could be achieved with AppConf, but I don't know that it's worth adding another dependency.

**Comment by spookylukey** [comment]
Closing for reasons described in the project README
