### ISSUE TITLE
Encrypted buttons don't work

### ISSUE THREAD

**Issue by trilogysci** [spookylukey/django-paypal#75]
Trying to get encrypted buttons to work but paypal responds with a strange error each time. The same non encrypted buttons work flawlessly. Tried both sandbox and production paypal endpoint each gives the error. 

      Sorry — your last action could not be completed

      If you were making a purchase or sending money, we recommend that you check both your PayPal account and your email for a transaction confirmation after 30 minutes.

      If you came to this page from another website, please return to that site (don't use your browser's Back button) and restart your activity.

      If you came from PayPal's website, click the PayPal logo in the upper-left corner to return to our home page and restart your activity. You might have to log in again.
      We are sorry, we are experiencing temporary difficulties. Please try again later. If this error occurred while making a payment, avoid duplicate payments by checking your Account Overview before resending a payment.

      For some browsers, this problem can be resolved by clearing or deleting cookies.

      Message 4001

**Comment by spookylukey** [comment]
I'm afraid there is nothing I can do to debug this. If you can show that django-paypal is doing something incorrectly, please re-open. This is a volunteer project and without a lot more info and debugging on your part, this isn't going to get fixed. Please re-open if you can provide a patch, or a unit test that would allow us to fix it.
