### ISSUE TITLE
Payment processed, IPN signal not received

### ISSUE THREAD

**Issue by ngn1123** [spookylukey/django-paypal#76]
I have an issue receiving the IPN signal, despite my payment successfully going through. With the recent version of django-paypal, the signals have been reduced to valid_ipn_received and invalid_ipn_received. I have two connectors to receive both signals and I've placed breakpoints on the methods, but the methods are never hit. Here is what I have so far:

In views.py:

    from django.shortcuts import render, render_to_response
    from django.http import HttpResponse
    from paypal.standard.forms import PayPalPaymentsForm
    from paypal.standard.models import ST_PP_COMPLETED
    from paypal.standard.ipn.signals import valid_ipn_received, invalid_ipn_received
    from django.views.decorators.csrf import csrf_exempt
    from django.conf import settings
    from django.core.urlresolvers import reverse
    import pdb
    
    def money_request(request):
        pdb.set_trace()
        # What you want the button to do.
        paypal_dict = {
            "business": settings.PAYPAL_RECEIVER_EMAIL,
            "item_name": "Event Registration",
            "notify_url": "http://localhost:8000/paypal/" + reverse('paypal-ipn'),
            "return_url": "http://localhost:8000/paypal/confirm",
            "cancel_return": "http://localhost:8000/paypal/",
    
        }
    
        # Create the instance.
        form = PayPalPaymentsForm(initial=paypal_dict)
        context = {"form": form}
        return render_to_response("paypal_test/payment.html", context)
    
    def show_me_the_money(sender, **kwargs):
        pdb.set_trace()
        ipn_obj = sender
        if ipn_obj.payment_status == ST_PP_COMPLETED:
            # Undertake some action depending upon `ipn_obj`.
            if ipn_obj.custom == "Upgrade all users!":
                Users.objects.update(paid=True)
        else:
            Users.objects.update(paid=False)
    
    @csrf_exempt
    def confirm(request):
        return render_to_response("confirm.html")
    
    valid_ipn_received.connect(show_me_the_money)
    
    invalid_ipn_received.connect(show_me_the_money)

I did read on the Paypal's IPN simulator that the simulator would not work for localhost, so I'm wondering if that is the same case for django-paypal, because I did not read this anywhere in the documentation.

Any help would be much appreciated.

Thanks!

**Comment by spookylukey** [comment]
That's right - the PayPal simulator, like real PayPal, and all similar online services, will not be able to access your localhost machine, unless it has a public IP address or name. This is due to how DNS works.

To test this, you need to use a service that will give you a public domain name. I would recommend https://ngrok.com/ 

See also this quick tutorial on using Django and ngrok: https://godjango.com/55-webhooks-django-and-ngrok/

You might also want to update your 'Site' record to the ngrok address, or ensure in some other way you are using the ngrok domain in your callback URL.

**Comment by ngn1123** [comment]
Thank you. That did the trick!
