### ISSUE TITLE
doDirectPayment not providing access to error code when throwing PayPalFailure

### ISSUE THREAD

**Issue by cspinelive** [spookylukey/django-paypal#78]
Is there a suggested way to gain access to the reason a doDirectPayment or createRecurringPaymentsProfile call has failed.  Currently a PayPalFailure is raised and swallowed by the PaymentForm.

Perhaps return the nvp_obj itself on success instead of True and raise the error instead of returning  False so our app can show a customized error message to the user about why paypal rejected the payment

**Comment by spookylukey** [comment]
The supported way is to use the `PayPalWPP` class directly, as in the [docs](https://django-paypal.readthedocs.org/en/stable/pro/detail.html#paypal.pro.helpers.PayPalWPP), or subclass the view/form to do what you need.

**Comment by cspinelive** [comment]
No problem.  Thanks for the library.  

Would you be interested in a pull request that added more friendly error info to the nvp_obj by interpreting the error code from the l_errorcode0 in the nvp response and matching it up with a dictionary of explanations mirroring what is found here?  https://developer.paypal.com/docs/classic/api/errorcodes/  The goal being to make it easier all around to show a better reason for the decline to the user.  

I guess there could be concern getting the phrases translated into other languages.  There's also a problem (for me at least) of the paypal phrases not being really what I'd want to show my customers.  They are better than nothing, but if I were do do it locally, I'd not mirror it exactly.

For example 15005 says "Processor Decline", "The transaction cannot be processed.",  and "The transaction was declined by the issuing bank, not PayPal. The merchant should attempt another card."   I'd probably convert it to something more customer friendly like "The credit card issuer has declined this transaction.  Call the number on the back of your card to find out more."

**Comment by cspinelive** [comment]
On second look.  doDirectPayment is in the model and is the one raising the PayPalFailure(nvp_obj.flag_info) exception before it gets to the form.

If it included the entire nvp_obj instead of only the flag_info.  Maybe I'm missing something, but I don't think dodirectpayment offers any way to get at the error code paypal is sending back.

**Comment by spookylukey** [comment]
Yes, looks right you are right, `doDirectPayment` is not being as helpful as it could here. The way forward would be to modify the exception class so that it can take `nvp_obj` as a keyword argument, and then add this in all the appropriate cases.

Adding a way to get the error messages would be a good addition - I think it should be done as a utility method/property add to `PayPalNVP`.

I won't have time to add this myself, but will accept a patch (if it includes some tests).

**Comment by spookylukey** [comment]
Because I needed it myself, I'm working on the exception containing the full NVP object.

**Comment by spookylukey** [comment]
This was fixed some time ago in 1893289f4d22e5e58f5e32f6bcbfa7df0abe51e4 .
