### ISSUE TITLE
Project doesn't work if I test with IPN Simulator

### ISSUE THREAD

**Issue by misalabs** [spookylukey/django-paypal#80]
Hello everyone!

I've been using the pluggeable application but if I test with the "Instant Paypment Notification simulator" (https://developer.paypal.com/webapps/developer/applications/ipn_simulator) the project says "Invalid form - no charset passed, can't decode" in the flag field.

I know the IPN Simulator doesn't send the "charset" parameter in the POST, and in the code, the project has a encoding validation so it could be a problem if I want to simulate payments with the IPN Simulator.

**Comment by spookylukey** [comment]
This is a bug in the IPN Simulator. It should be doing the same thing as the real IPN and sending a charset. This bug should be reported to PayPal. I think in the past I did this and they fixed it, but it seems to be broken again.

There is no point adding workarounds for the IPN simulator - that just increases the chances that something works on the simulator but not in real life.

**Comment by misalabs** [comment]
Yeah, It's rasonable. Thanks @spookylukey

**Comment by tapper2** [comment]
asddsa
