### ISSUE TITLE
valid_ipn_received.connect(show_me_the_money) has never called.

### ISSUE THREAD

**Issue by shinriyo** [spookylukey/django-paypal#81]
I tried the code in the page
http://django-paypal.readthedocs.org/en/latest/standard/ipn.html

I certainly added the valid_ipn_received.connect(show_me_the_money) in my views.py
But, show_me_the_money has never called.
Is it bug?

**Comment by spookylukey** [comment]
This function works as advertised. Please use the PayPal sandbox to ensure that you are wiring up the IPN view correctly.

**Comment by shinriyo** [comment]
Yes. I use PayPal sandbox.
show_me_the_money
Users class is User?
How to define the user who bought via Paypal?

**Comment by shinriyo** [comment]
urls.py
                       url(r'^payment-url/$',
                           login_required(view_that_asks_for_money), name='paypal'),

I found

http://w3facility.org/question/django-paypal-does-not-receive-ipn-signal/

**Comment by spookylukey** [comment]
I'm guessing that you are attempting to test on localhost, without using something like ngrok.

I've added a section to the bottom of the docs about this: https://github.com/spookylukey/django-paypal/blob/master/docs/standard/ipn.rst

**Comment by shinriyo** [comment]
Thank you for replying and telling me ngrok, the useful service.
But, I don't use localhost. I use public IP address. And I also use sandbox.
I read your additional document. My server protected by firewall.
I'd like to open port, but what number of port must I open?

**Comment by shinriyo** [comment]
Hello spookylukey

I tried ngrok. But, valid_ipn_received.connect didn't work.

I pushed the my minimum project on my github

https://github.com/shinriyo/paypal_test

**Comment by shinriyo** [comment]
The code is not be called.

https://github.com/shinriyo/paypal_test/blob/master/paypal_test/urls.py#L36

**Comment by spookylukey** [comment]
No, I can't tell you what is wrong, because I don't know! I'm afraid I can't provide any more help for this.

**Comment by shinriyo** [comment]
I found what I should have set the setting in my PayPal site.
The setting was hard to find for me such as non-native English speaker.
I spend about one week to resolve. So, I was impatient. I'm sorry.

**Comment by techietek** [comment]
@shinriyo what was the issue as I am seeing the same problem?
