### ISSUE TITLE
PAYPAL_IDENTITY_TOKEN is required?

### ISSUE THREAD

**Issue by shinriyo** [spookylukey/django-paypal#82]
I don't use PDT.
So, I didn't added 'paypal.standard.pdt', in my settings.py.
But, Django's error says it requires PAYPAL_IDENTITY_TOKEN.

**Comment by spookylukey** [comment]
Perhaps you have imported `paypal.standard.pdt` somewhere? I can't explain this otherwise.

**Comment by shinriyo** [comment]
I didn't import "paypal.standard.pdt".
I imported only 'paypal.standard.ipn'.
Perhaps, it also require PAYPAL_IDENTITY_TOKEN?
I commented out it.
And, in the database, only paypal_ipn table exists.
I dropped other table which created when I imported paypal.standard.pdt.

**Comment by shinriyo** [comment]
I'm sorry. I resolved!
I found what was mistook!

I added below in my urls.py.

(r'^paypal/pdt/', include('paypal.standard.pdt.urls')),

it disturbed.

**Comment by shinriyo** [comment]
It is close okey.
