### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by shinriyo** [spookylukey/django-paypal#85]
I tried PDT.

I added
`url(r'^money/', 'paypal.standard.pdt.views.pdt', name='return-location'),`
in my urks.py.

But, pdt.html has bug.
Did you added base.html?
or must I add base.html myself?

packages/paypal/standard/pdt/templates/pdt/pdt.html, error at line 1
base.html
1	{% extends "base.html" %}

**Comment by spookylukey** [comment]
Yep, you need to add `base.html` yourself. This needs to be added to the docs.

**Comment by spookylukey** [comment]
Fixed in 2bfc430ffc1e5e2e44b57aeffe7d1f961ebf1e1e
