### ISSUE TITLE
Note for documentation re: upgrading to Django 1.7/1.8 and database upgrade

### ISSUE THREAD

**Issue by photojosh** [spookylukey/django-paypal#88]
I was going through my app upgrading to 1.8 from 1.4 (LTS support) and django-paypal 1.2 to 2.1 and freaked out when I got to the django-paypal database upgrade instructions saying I had to do all the migrations *before* the Django 1.8 upgrade.

I figured out quickly fortunately that I could run:

./manage.py migrate ipn --fake-initial

and it did the job just fine. 

Might be worthwhile adding this to the docs.

**Comment by spookylukey** [comment]
I think it kind of depends on which version of django-paypal you started with. I don't want to add something to the docs which misguides people. If we can work out when this is safe, I'm happy to add it.

**Comment by photojosh** [comment]
Fair enough... this is probably reference enough now anyway if they start looking.
