### ISSUE TITLE
Documentation for issue with upg

### ISSUE THREAD

**Issue by photojosh** [spookylukey/django-paypal#89]
The release notes don't state that at some point (looking at the history, I believe it to be v2.0, but I'm upgrading from 1.2 so can't easily tell), settings.PAYPAL_TEST=False was introduced, but also became mandatory for production use, which changed the default behaviour.

This bit me because I tested and everything was fine using the sandbox. I was setting a settings.PRODUCTION=True/False and calling form.render() for the former and form.sandbox() for the latter. This broke.

(like with my previous issue, this may be fine to just close and leave standing as documentation for anyone encountering this problem)

**Comment by spookylukey** [comment]
Fixed in 2d71847e01b8de2609cc58fe92edb36550ee51a4
