### ISSUE TITLE
Using Protected Payment Buttons option

### ISSUE THREAD

**Issue by chrismaille** [spookylukey/django-paypal#98]
Instead of rendering the form with all data (public acessible on html), such as:

a3: 19.99
p2: 1
t3: M
business: myemail@example.com

can we use a protected button, created on paypal site, and our paypal_dict can be like:

button_url: sandbox or live url
hosted_button_id: the button created ID

**Comment by spookylukey** [comment]
I believe this is answered in the docs:

https://django-paypal.readthedocs.org/en/stable/standard/encrypted_buttons.html

I have never tried this myself, so don't know if it works. If it doesn't, or needs fixing, please let me know (preferably in the form of a pull request) and I'll fix it.

If that is about something different, then as far as I know we don't support it. django-paypal is Open Source and has no team actively developing (I maintain existing functionality), so if you would like support for this to be added, it will be up to you (or someone you can persuade to do it) to implement it.
